name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js, npm, and Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
      - run: npm ci
      - run: npm run build
      - run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
